### ISSUE TITLE
Misleading deprecation message for minimumDef

### ISSUE THREAD

**Issue by crclark** [ndmitchell/safe#30] opened 2020-05-24 19:49 UTC
Using `minimumDef` gives this warning:

```
Deprecated: "Use @minimumBound@ instead."
```

`minimumBound` has the same type signature, so I thought this was just a rename. However, they return different results:

```
> minimumDef 0 [1,2,3]
1
> minimumBound 0 [1,2,3]
0
```

**Comment by ndmitchell** [comment] 2020-05-24 20:11
On reflection, and given your code, I think deprecating the old versions and moving people is highly likely to break a lot of code by accident. Therefore my inclination is to move these functions to discouraged for new use, and then existing users are better of still using them than moving.

**Comment by ndmitchell** [comment] 2020-05-24 20:22
safe-0.3.19 now out which doesn't deprecate these stuff, thus doesn't have DEPRECATE messages which can be misleading. The arguments for moving to minimumBound etc are set out in https://github.com/ndmitchell/safe/issues/26 - I leave it to your choice as to how compelling you find them. CC @minad who originally deprecated these functions.

**Closed** 2020-05-24 20:23 UTC

**Comment by crclark** [comment] 2020-05-24 20:42
Thanks! For what it's worth, I replaced my usage of `minimumDef` with its definition: `fromMaybe x (minimumMay xs)`, but I think that `minimumDef` has value. It does what I need and `minimumBound` doesn't, so it isn't immediately obvious to me why it should be deprecated.

**Comment by minad** [comment] 2020-05-24 21:32
I argued before that from an algebraic point of view the minimumBound functions etc make sense and minimumDef does not. See here https://github.com/ndmitchell/safe/issues/26

I still believe the minimumDef functions should be deprecated.

But the deprecation messages should definitely be improved, including some explanation. In particular since it happened now for the second time that stumbled over this. I am sorry for that!

@crclark Where are you using minimumDef, while minimumBound would not make sense?

**Comment by crclark** [comment] 2020-05-24 22:46
@minad You seem to be right! I was halfway through describing my use case when I realized that my use of `minimumDef` is actually obscuring a bug in an improbable edge case of my code. I can't actually think of a case where `minimumDef` would be useful. It seems quite likely to me that using it will always hide bugs. In my case, though, the correct fix is not to use `minimumBound`, but instead to modify my function to return `NonEmptyList` and then call `minimum` on that.

Sadly, though, your original argument did little to convince me. Unfortunately, I still don't know how to improve that argument. I had to go through the exercise of trying to explain why `minimumDef` was reasonable for my use case to understand that it was not. :laughing: Thank you for asking me to explain myself!

In case anyone who later reads this issue is interested in an example of how `minimumDef` can mislead the unwary, I will briefly describe a (highly simplified version of) my use case here. I have a set of workers consuming a list of messages. The workers are fault-tolerant, and checkpoint the index of the last message they consumed. If a worker hasn't written a checkpoint yet, I assume it is at the beginning of the list. I wanted to find the minimum of all the checkpoints (assume that I want to delete messages that all workers have already consumed, for example). I had an IO action to get the checkpoints of all the workers, `getCheckpoints :: IO [Checkpoint]`. I had falsely assumed that this would either return 0 elements (when the system had just started and no worker has persisted a checkpoint yet) or n elements (after the workers have begun consuming messages). In the first case, I wanted to return `minBound`. In the second case, the minimum checkpoint. Hence, `minimumDef minBound checkpoints`. Obviously, though, there is a brief period of time when the system starts where some workers have started working and written their first checkpoint and other workers have not yet started working, and my list will contain fewer than `n` checkpoints. In that case, I must still return `minBound`, to account for workers that haven't started yet. By using `minimumDef`, I was returning the minimum checkpoint of the workers which had started, incorrectly ignoring the workers which had not. So, the correct solution is to modify `getCheckpoints` to guarantee it always returns `n` checkpoints, substituting `minBound` for any workers who have not yet written their checkpoint.

**Comment by minad** [comment] 2020-05-25 10:24
> Sadly, though, your original argument did little to convince me. Unfortunately, I still don't know how to improve that argument.

The question is if we prefer lawful functions over ones without laws. This is the same issue with typeclassen. I very much prefer classes for which reasonable laws can be given, otherwise it is just ad-hoc overloading. 

If we look at minimumDef - this is just the trivial combination of fromMaybe and minimumMay without any additional guarantees. Therefore minimumDef should not be provided.

In contrast, minimumBound gives you more than that. `minimumBound b xs <= b` holds for all xs, even the empty list. This is the same as a fold over the list with the bounded `Min` monoid with identity `Min b`.

When I used minimumDef in my intro prelude, I actually expected it to behave as such due to these arguments. But it did not and I had a bug due to that.

**Comment by gbaz** [comment] 2021-10-03 18:51
Just for the record, someone doing a big bump of stuff on our codebase followed the deprecation message and caused a massive regression on a number of production systems that it took me some days to track down. I'm glad this is now being undone.

`maximumBound` is nice, but was not _at all_ what I wanted. The code in question read something like `maximumDef 0 listOfDelays` -- and the intended semantics is to compute the greatest delay amongst the delays, and quite correctly, when there's an empty list, then there should be no delay. The big version-bump pr rather blindly followed the deprecation advice, creating a situation where there was _never_ a computed delay, and hence where our "here's how to recover from a delay" situation never kicked in, grinding some rather large systems to a halt.

In any case, glad this is now reverted, and consider the above a good argument for why people who Know What They Are Doing could well want the `Def` rather than `Bound` functions.

**Comment by ndmitchell** [comment] 2021-10-04 19:56
Thanks for the info @gbaz - given the severity I've marked 0.3.18 (the only version with the deprecation message in) as deprecated itself, to discourage Cabal from picking it.
